### ISSUE TITLE
Segfault: heldObject is nullptr

### ISSUE THREAD

**Issue by Shaac** [jasonrohrer/OneLife#10]
The game crashed as I was taking and dropping objects.
gdb tells me that `heldObject` is null when accessed with `heldObject->rideable`.
I used a client that I compiled with the pullAndBuildLatest script. The version is `OneLife_v64`.
Here is the call stack:

```
#0  0x000055555559c2bf in LivingLifePage::drawLiveObject (this=0x5555589875c0, inObj=0x55555cfcd9d8, inSpeakers=0x7fffffffd240, inSpeakersPos=0x7fffffffd220) at LivingLifePage.cpp:2864
#1  0x00005555555a0eb9 in LivingLifePage::draw (this=0x5555589875c0, inViewCenter=..., inViewSize=1280) at LivingLifePage.cpp:4458
#2  0x000055555559286d in GamePage::base_draw (this=0x5555589875c0, inViewCenter=..., inViewSize=1280) at GamePage.cpp:320
#3  0x0000555555565c5a in drawFrameNoUpdate (inUpdate=1 '\001') at game.cpp:1753
#4  0x0000555555565bc0 in drawFrame (inUpdate=1 '\001') at game.cpp:1735
#5  0x0000555555646414 in GameSceneHandler::drawScene (this=0x555555adb340) at ../../minorGems/game/platforms/SDL/gameSDL.cpp:3044
#6  0x0000555555614866 in callbackDisplay () at ../../minorGems/graphics/openGL/ScreenGL_SDL.cpp:2766
#7  0x00005555556131e5 in ScreenGL::start (this=0x55555595eb40) at ../../minorGems/graphics/openGL/ScreenGL_SDL.cpp:2007
#8  0x00005555556451da in mainFunction (inNumArgs=1, inArgs=0x7fffffffe288) at ../../minorGems/game/platforms/SDL/gameSDL.cpp:2472
#9  0x00005555556408c0 in main (inArgCount=1, inArgs=0x7fffffffe288) at ../../minorGems/game/platforms/SDL/gameSDL.cpp:23

```

**Comment by jasonrohrer** [comment]
This was fixed in v65.  Thanks for the report!
