### ISSUE TITLE
Attempting to view email before it has been set on services page causes segfault

### ISSUE THREAD

**Issue by cydlee** [jasonrohrer/OneLife#1085]
Steps to reproduce:
1. `echo "" > email.ini`
2. Start the client and go to [SERVICES] page.
3. Click [VIEW] to view email. This should cause a segfault.

I tested this on Pop!_OS 22.04 LTS.

Output of gdb:
```
Thread 1 "OneLifeApp" received signal SIGSEGV, Segmentation fault.
__strcmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:115
115	../sysdeps/x86_64/multiarch/strcmp-avx2.S: No such file or directory.
(gdb) bt
#0  __strcmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:115
#1  0x00005555556b4a3e in TranslationManager::translate (inTranslationKey=0x0) at ../../minorGems/util/TranslationManager.cpp:133
#2  0x00005555556e79c0 in translate (inTranslationKey=0x0) at ../../minorGems/game/platforms/SDL/gameSDL.cpp:4376
#3  0x00005555555ab4c3 in drawMessage (inTranslationKey=0x0, inCenter=..., inRed=0 '\000', inFade=1) at message.cpp:28
#4  0x00005555556809e0 in ServicesPage::draw (this=0x5555564164a0, inViewCenter=..., inViewSize=1280) at ServicesPage.cpp:167
#5  0x00005555555afc30 in GamePage::base_draw (this=0x5555564164a0, inViewCenter=..., inViewSize=1280) at GamePage.cpp:320
#6  0x000055555556cf8b in drawFrameNoUpdate (inUpdate=1 '\001') at game.cpp:2580
#7  0x000055555556ced7 in drawFrame (inUpdate=1 '\001') at game.cpp:2562
#8  0x00005555556e4cc0 in GameSceneHandler::drawScene (this=0x555555b07e10) at ../../minorGems/game/platforms/SDL/gameSDL.cpp:3313
#9  0x00005555556af285 in callbackDisplay () at ../../minorGems/graphics/openGL/ScreenGL_SDL.cpp:2906
#10 0x00005555556ada34 in ScreenGL::start (this=0x555555828f10) at ../../minorGems/graphics/openGL/ScreenGL_SDL.cpp:2122
#11 0x00005555556e361c in mainFunction (inNumArgs=1, inArgs=0x7fffffffdf88) at ../../minorGems/game/platforms/SDL/gameSDL.cpp:2624
#12 0x00005555556de372 in main (inArgCount=1, inArgs=0x7fffffffdf88) at ../../minorGems/game/platforms/SDL/gameSDL.cpp:23
```
I'm not 100% sure if this is the cause, but my guess is that the value of `userEmail` is `NULL` at the time `drawMessage( userEmail, pos )` is called (`OneLife/gameSource/ServicesPage.cpp:167`).

**Comment by jasonrohrer** [comment]
Great catch, thank you!
